version: '3.7'
services:
  # service 1
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    container_name: mssql
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd

  # service 2
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    network_mode: bridge
    expose:
      - 6379
    # service 3
  api:
    build: .
    container_name: bpa_api
    restart: unless-stopped
    network_mode: bridge
    expose:
      - 8080
    volumes:
      - .:/src
      - /src/node_modules
    command: npm run start:dev
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    depends_on:
      - mssql
    links:
      - redis
      - mssql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
      - "443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
      - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
    links:
      - api
    env_file: ./.env
